// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBooking.API.Data;

#nullable disable

namespace MovieBooking.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517085725_AddQuanLyRapModule")]
    partial class AddQuanLyRapModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieBooking.API.Entities.Banner", b =>
                {
                    b.Property<int>("MaBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanner"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.HasKey("MaBanner");

                    b.HasIndex("MaPhim");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.CumRap", b =>
                {
                    b.Property<string>("MaCumRap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaHeThongRap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenCumRap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaCumRap");

                    b.HasIndex("MaHeThongRap");

                    b.ToTable("CumRap");

                    b.HasData(
                        new
                        {
                            MaCumRap = "bhd-star-bitexco",
                            DiaChi = "L3-Bitexco Icon 68, 2 Hai Trieu, Q1",
                            MaHeThongRap = "BHDStar",
                            TenCumRap = "BHD Star Bitexco"
                        },
                        new
                        {
                            MaCumRap = "cgv-su-van-hanh",
                            DiaChi = "T?ng 6 V?n H?nh Mall, Qu?n 10",
                            MaHeThongRap = "CGV",
                            TenCumRap = "CGV Sư V?n H?nh"
                        });
                });

            modelBuilder.Entity("MovieBooking.API.Entities.HeThongRap", b =>
                {
                    b.Property<string>("MaHeThongRap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BiDanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenHeThongRap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHeThongRap");

                    b.ToTable("HeThongRap");

                    b.HasData(
                        new
                        {
                            MaHeThongRap = "BHDStar",
                            BiDanh = "bhd-star-cineplex",
                            Logo = "https://movienew.cybersoft.edu.vn/hinhanh/bhd-star-cineplex.png",
                            TenHeThongRap = "BHD Star Cineplex"
                        },
                        new
                        {
                            MaHeThongRap = "CGV",
                            BiDanh = "cgv",
                            Logo = "https://movienew.cybersoft.edu.vn/hinhanh/cgv.png",
                            TenHeThongRap = "CGV"
                        });
                });

            modelBuilder.Entity("MovieBooking.API.Entities.LichChieu", b =>
                {
                    b.Property<int>("MaLichChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichChieu"));

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<string>("MaRap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayChieuGioChieu")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaRap");

                    b.ToTable("LichChieu");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.LoaiNguoiDung", b =>
                {
                    b.Property<string>("MaLoaiNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiNguoiDung");

                    b.ToTable("LoaiNguoiDung");

                    b.HasData(
                        new
                        {
                            MaLoaiNguoiDung = "QuanTri",
                            TenLoai = "Qu?n Tr?"
                        },
                        new
                        {
                            MaLoaiNguoiDung = "KhachHang",
                            TenLoai = "Khách Hàng"
                        });
                });

            modelBuilder.Entity("MovieBooking.API.Entities.NguoiDung", b =>
                {
                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLoaiNguoiDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaLoaiNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhim"));

                    b.Property<string>("BiDanh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DangChieu")
                        .HasColumnType("bit");

                    b.Property<int>("DanhGia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Hot")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SapChieu")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Trailer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaPhim");

                    b.HasIndex("BiDanh");

                    b.HasIndex("NgayKhoiChieu");

                    b.ToTable("Phim");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.RapPhim", b =>
                {
                    b.Property<string>("MaRap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaCumRap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenRap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaRap");

                    b.HasIndex("MaCumRap");

                    b.ToTable("RapPhim");

                    b.HasData(
                        new
                        {
                            MaRap = "rap-001",
                            MaCumRap = "bhd-star-bitexco",
                            TenRap = "R?p 1"
                        },
                        new
                        {
                            MaRap = "rap-002",
                            MaCumRap = "cgv-su-van-hanh",
                            TenRap = "R?p 2"
                        });
                });

            modelBuilder.Entity("MovieBooking.API.Entities.Banner", b =>
                {
                    b.HasOne("MovieBooking.API.Entities.Phim", "Phim")
                        .WithMany("Banners")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.CumRap", b =>
                {
                    b.HasOne("MovieBooking.API.Entities.HeThongRap", "HeThongRap")
                        .WithMany("CumRaps")
                        .HasForeignKey("MaHeThongRap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeThongRap");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.LichChieu", b =>
                {
                    b.HasOne("MovieBooking.API.Entities.Phim", "Phim")
                        .WithMany()
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooking.API.Entities.RapPhim", "RapPhim")
                        .WithMany("LichChieus")
                        .HasForeignKey("MaRap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("RapPhim");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.NguoiDung", b =>
                {
                    b.HasOne("MovieBooking.API.Entities.LoaiNguoiDung", "LoaiNguoiDung")
                        .WithMany()
                        .HasForeignKey("MaLoaiNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiNguoiDung");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.RapPhim", b =>
                {
                    b.HasOne("MovieBooking.API.Entities.CumRap", "CumRap")
                        .WithMany("Raps")
                        .HasForeignKey("MaCumRap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CumRap");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.CumRap", b =>
                {
                    b.Navigation("Raps");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.HeThongRap", b =>
                {
                    b.Navigation("CumRaps");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.Phim", b =>
                {
                    b.Navigation("Banners");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.RapPhim", b =>
                {
                    b.Navigation("LichChieus");
                });
#pragma warning restore 612, 618
        }
    }
}
