// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBooking.API.Data;

#nullable disable

namespace MovieBooking.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517075618_AddPhimAndBannerManagement")]
    partial class AddPhimAndBannerManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieBooking.API.Entities.Banner", b =>
                {
                    b.Property<int>("MaBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanner"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.HasKey("MaBanner");

                    b.HasIndex("MaPhim");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.LoaiNguoiDung", b =>
                {
                    b.Property<string>("MaLoaiNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiNguoiDung");

                    b.ToTable("LoaiNguoiDung");

                    b.HasData(
                        new
                        {
                            MaLoaiNguoiDung = "QuanTri",
                            TenLoai = "Qu?n Tr?"
                        },
                        new
                        {
                            MaLoaiNguoiDung = "KhachHang",
                            TenLoai = "Khách Hàng"
                        });
                });

            modelBuilder.Entity("MovieBooking.API.Entities.NguoiDung", b =>
                {
                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLoaiNguoiDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaLoaiNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhim"));

                    b.Property<string>("BiDanh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DangChieu")
                        .HasColumnType("bit");

                    b.Property<int>("DanhGia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Hot")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SapChieu")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Trailer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaPhim");

                    b.HasIndex("BiDanh");

                    b.HasIndex("NgayKhoiChieu");

                    b.ToTable("Phim");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.Banner", b =>
                {
                    b.HasOne("MovieBooking.API.Entities.Phim", "Phim")
                        .WithMany("Banners")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.NguoiDung", b =>
                {
                    b.HasOne("MovieBooking.API.Entities.LoaiNguoiDung", "LoaiNguoiDung")
                        .WithMany()
                        .HasForeignKey("MaLoaiNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiNguoiDung");
                });

            modelBuilder.Entity("MovieBooking.API.Entities.Phim", b =>
                {
                    b.Navigation("Banners");
                });
#pragma warning restore 612, 618
        }
    }
}
